version: '3.5'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "chad"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  run_local:
    command: ["/usr/local/bin/python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DEBUG: "1"
      DB_NAME: "chad"
      DB_HOST: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
volumes:
  postgresql:
